name: Cron Test V2

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test schedule
        run: |
          echo "Triggered by schedule"
          date -u
